# Generated by Django 3.1 on 2020-08-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
