# Generated by Django 3.1 on 2020-09-02 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200828_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 2, 20, 23, 26, 421213)),
        ),
    ]
