# Generated by Django 3.1 on 2020-08-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20200825_1941'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allowed_doctor',
            field=models.ManyToManyField(null=True, to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rating',
            field=models.ManyToManyField(null=True, to='patient.Rating'),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='institute',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
