# Generated by Django 3.1 on 2020-08-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_appointment_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='appointment_time',
        ),
    ]
