# Generated by Django 3.1 on 2020-08-27 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20200827_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 12, 17, 24, 372989)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 13, 17, 24, 372962)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='prev_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 12, 17, 24, 373043)),
        ),
    ]
