# Generated by Django 3.1 on 2020-08-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20200825_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.ManyToManyField(blank=True, to='doctor.Education'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ManyToManyField(blank=True, to='doctor.Hospital'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.ManyToManyField(blank=True, to='doctor.Specialities'),
        ),
    ]
