# Generated by Django 3.1 on 2020-08-26 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20200825_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='contact',
        ),
    ]
