# Generated by Django 3.1 on 2020-08-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_doctor_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rate',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
