# Generated by Django 3.1 on 2020-09-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctor_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': [('isDoctor', 'Can open doctor tabs')]},
        ),
    ]
